[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npx serve dist --listen $PORT --single --no-clipboard"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
